"""add official documents and embeddings tables

Revision ID: 57110c42edff
Revises: 8727e7fb4ae0
Create Date: 2025-11-21 09:33:35.296308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57110c42edff'
down_revision: Union[str, None] = '8727e7fb4ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


