"""add_documents_and_document_embeddings

Revision ID: 8727e7fb4ae0
Revises: b4803692e83f
Create Date: 2025-11-21 09:02:25.515132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8727e7fb4ae0'
down_revision: Union[str, None] = 'b4803692e83f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


