"""add_calendars_and_calendar_events

Revision ID: a9167f23d1a9
Revises: 57110c42edff
Create Date: 2025-11-21 11:01:07.936555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9167f23d1a9'
down_revision: Union[str, None] = '57110c42edff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Verificar se a tabela já existe usando SQL direto
    conn = op.get_bind()
    result = conn.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'calendars'
        );
    """))
    calendars_exists = result.scalar()
    
    if not calendars_exists:
        op.create_table(
            'calendars',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('user_id', sa.UUID(), nullable=False),
            sa.Column('title', sa.String(length=255), nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('group_number', sa.Integer(), nullable=True),
            sa.Column('name_in_calendar', sa.String(length=255), nullable=True),
            sa.Column('position_in_list', sa.String(length=10), nullable=True),
            sa.Column('start_date', sa.Date(), nullable=False),
            sa.Column('end_date', sa.Date(), nullable=False),
            sa.Column('source_file', sa.String(length=500), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_calendars_user_id'), 'calendars', ['user_id'], unique=False)
    
    result = conn.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'calendar_events'
        );
    """))
    events_exists = result.scalar()
    
    if not events_exists:
        op.create_table(
            'calendar_events',
            sa.Column('id', sa.UUID(), nullable=False),
            sa.Column('calendar_id', sa.UUID(), nullable=False),
            sa.Column('event_type', sa.String(length=50), nullable=False),
            sa.Column('event_date', sa.Date(), nullable=False),
            sa.Column('day_of_week', sa.String(length=10), nullable=True),
            sa.Column('start_time', sa.Time(), nullable=True),
            sa.Column('end_time', sa.Time(), nullable=True),
            sa.Column('location', sa.String(length=255), nullable=True),
            sa.Column('shift_type', sa.String(length=50), nullable=True),
            sa.Column('notes', sa.Text(), nullable=True),
            sa.Column('week_number', sa.Integer(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_calendar_events_calendar_id'), 'calendar_events', ['calendar_id'], unique=False)
        op.create_index(op.f('ix_calendar_events_event_date'), 'calendar_events', ['event_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_events_event_date'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_calendar_id'), table_name='calendar_events')
    op.drop_table('calendar_events')
    op.drop_index(op.f('ix_calendars_user_id'), table_name='calendars')
    op.drop_table('calendars')
    # ### end Alembic commands ###


