"""add_preceptor_to_calendar_events

Revision ID: cfd74c38ad07
Revises: a9167f23d1a9
Create Date: 2025-11-21 11:37:25.815483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfd74c38ad07'
down_revision: Union[str, None] = 'a9167f23d1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('preceptor', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_events', 'preceptor')
    # ### end Alembic commands ###


